### ISSUE TITLE
Не компилируются библиотека

### ISSUE THREAD

**Issue by akonoplev** [tinkoff-mobile-tech/TinkoffID-iOS#17]
Привет!

установил как SwiftPM зависимость

<img width="420" alt="image" src="https://user-images.githubusercontent.com/26434897/209117569-8644333d-ab2a-4a0e-85ae-98fecf9047f6.png">

но библиотека не компилируется из за отсутствующего импорта UIKit судя по всему

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/26434897/209117881-73bc8e0b-7fb8-43ca-9257-e161fe09d50b.png">

В тоже время если поставить зависимость через сocoa pods проблемы нету

**Comment by daivlev** [comment]
Исправлено в 1.2.1
